# These are supported funding model platforms

github: [simeononsecurity]
custom: ['https://simeononsecurity.ch']
custom: ['https://simeononsecurity.ch/recommendations']
custom: ['https://cybersentinels.org']
custom: ['https://discord.io/cybersentinels']
