# These are supported funding model platforms

github: [simeononsecurity]
custom: ['https://simeononsecurity.com','https://simeononsecurity.com/recommendhome', 'https://simeononsecurity.com/affiliate', 'https://twitter.com/simeonsecurity','https://discord.io/cybersentinels']
