# These are supported funding model platforms

github: [simeononsecurity]
custom: ['https://simeononsecurity.ch','https://simeononsecurity.ch/recommendhome', 'https://simeononsecurity.ch/affiliate', 'https://twitter.com/simeonsecurity','https://discord.io/cybersentinels']
