# These are supported funding model platforms

github: [simeononsecurity]
custom: ['https://simeononsecurity.ch','https://simeononsecurity.ch/recommendations','https://cybersentinels.org','https://discord.io/cybersentinels']
