name: Daily README Update

on:
  schedule:
    - cron: '0 0 * * *' # Schedule the workflow to run daily at midnight (UTC)
  push:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README from RSS feed
        id: update-readme
        uses: sarisia/actions-readme-feed@v1
        with:
          url: 'https://simeononsecurity.ch/index.xml'
          file: 'README.md'
          
      - if: ${{ steps.update-readme.outputs.changed == true }}
      - name: Commit changes
        uses: mikeal/publish-to-github-action@v1
        with:
          github_token: ${{ secrets.ghtoken }}
