name: Daily README Update

on:
  schedule:
    - cron: '0 0 * * *' # Schedule the workflow to run daily at midnight (UTC)
  push:
    branches:
      - main # Specify the branch where you want the workflow to run on push

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README from RSS feed
        uses: sarisia/actions-readme-feed@v1
        with:
          url: 'https://simeononsecurity.ch/index.xml'
          file: 'README.md'
      - if: ${{ steps.feed.outputs.changed == true }}
        uses: sarisia/actions-commit@master
